name: odontoradiosis_interfaces
description: The global required interfaces used by Odontoradiosis services
version: 0.0.1
homepage: https://github.com/jictyvoo/odontoradiosis

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  # Nothing imported

dev_dependencies:
  lints: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
